///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace TestDemo
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the TestDemoRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("a8242e29-6903-46ab-beba-e680851744b8")]
    public partial class TestDemoRepository : RepoGenBaseFolder
    {
        static TestDemoRepository instance = new TestDemoRepository();
        TestDemoRepositoryFolders.ApplicationUnderTestAppFolder _applicationundertest;

        /// <summary>
        /// Gets the singleton class instance representing the TestDemoRepository element repository.
        /// </summary>
        [RepositoryFolder("a8242e29-6903-46ab-beba-e680851744b8")]
        public static TestDemoRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public TestDemoRepository() 
            : base("TestDemoRepository", "/", null, 0, false, "a8242e29-6903-46ab-beba-e680851744b8", ".\\RepositoryImages\\TestDemoRepositorya8242e29.rximgres")
        {
            _applicationundertest = new TestDemoRepositoryFolders.ApplicationUnderTestAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("a8242e29-6903-46ab-beba-e680851744b8")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The ApplicationUnderTest folder.
        /// </summary>
        [RepositoryFolder("bc0d247c-2729-489d-b18f-6587ed171c9f")]
        public virtual TestDemoRepositoryFolders.ApplicationUnderTestAppFolder ApplicationUnderTest
        {
            get { return _applicationundertest; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class TestDemoRepositoryFolders
    {
        /// <summary>
        /// The ApplicationUnderTestAppFolder folder.
        /// </summary>
        [RepositoryFolder("bc0d247c-2729-489d-b18f-6587ed171c9f")]
        public partial class ApplicationUnderTestAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _buttonnewInfo;
            RepoItemInfo _estimateInfo;
            RepoItemInfo _ratesresourcesInfo;
            RepoItemInfo _somelistInfo;
            RepoItemInfo _partclosebuttonInfo;
            RepoItemInfo _somecontainerInfo;

            /// <summary>
            /// Creates a new ApplicationUnderTest  folder.
            /// </summary>
            public ApplicationUnderTestAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ApplicationUnderTest", "/form[@processname='Estimator']", parentFolder, 30000, null, true, "bc0d247c-2729-489d-b18f-6587ed171c9f", "")
            {
                _buttonnewInfo = new RepoItemInfo(this, "ButtonNew", "?/?/container[@automationid='PART_AutoHideControl']/list/list[1]/?/?/container[@automationid='PART_ItemsPresenter']/button[@text='New']", 30000, null, "254c8401-b078-48a3-b079-cfddaa5e5f6b");
                _estimateInfo = new RepoItemInfo(this, "Estimate", "?/?/container[@automationid='PART_AutoHideControl']/container[@automationid='PART_HeaderAndTabsLayout']/list[@automationid='PART_PageCategoriesPane']//text[@caption='Estimate']", 30000, null, "bfd17eb8-4cd4-4117-99b6-0d8a113c4e23");
                _ratesresourcesInfo = new RepoItemInfo(this, "RatesResources", "?/?/container[@automationid='PART_AutoHideControl']/container[@automationid='PART_HeaderAndTabsLayout']/list[@automationid='PART_PageCategoriesPane']//text[@caption='Rates & Resources']", 30000, null, "ca1e5c3b-5bde-47e6-8bfc-aa9f0544c090");
                _somelistInfo = new RepoItemInfo(this, "SomeList", "contextmenu/list[5]", 30000, null, "895d9abf-2c7b-455a-9132-0782825fd80f");
                _partclosebuttonInfo = new RepoItemInfo(this, "PARTCloseButton", ".//button[@automationid='PART_ShowModeSelector']/button[@automationid='PART_CloseButton']", 30000, null, "873f6d9e-7106-4848-9b09-d43163698f2c");
                _somecontainerInfo = new RepoItemInfo(this, "SomeContainer", "contextmenu/container[1]", 30000, null, "572f62e6-c31e-4fd5-9cc4-47aae36d2a4e");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("bc0d247c-2729-489d-b18f-6587ed171c9f")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("bc0d247c-2729-489d-b18f-6587ed171c9f")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ButtonNew item.
            /// </summary>
            [RepositoryItem("254c8401-b078-48a3-b079-cfddaa5e5f6b")]
            public virtual Ranorex.Button ButtonNew
            {
                get
                {
                    return _buttonnewInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonNew item info.
            /// </summary>
            [RepositoryItemInfo("254c8401-b078-48a3-b079-cfddaa5e5f6b")]
            public virtual RepoItemInfo ButtonNewInfo
            {
                get
                {
                    return _buttonnewInfo;
                }
            }

            /// <summary>
            /// The Estimate item.
            /// </summary>
            [RepositoryItem("bfd17eb8-4cd4-4117-99b6-0d8a113c4e23")]
            public virtual Ranorex.Text Estimate
            {
                get
                {
                    return _estimateInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Estimate item info.
            /// </summary>
            [RepositoryItemInfo("bfd17eb8-4cd4-4117-99b6-0d8a113c4e23")]
            public virtual RepoItemInfo EstimateInfo
            {
                get
                {
                    return _estimateInfo;
                }
            }

            /// <summary>
            /// The RatesResources item.
            /// </summary>
            [RepositoryItem("ca1e5c3b-5bde-47e6-8bfc-aa9f0544c090")]
            public virtual Ranorex.Text RatesResources
            {
                get
                {
                    return _ratesresourcesInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The RatesResources item info.
            /// </summary>
            [RepositoryItemInfo("ca1e5c3b-5bde-47e6-8bfc-aa9f0544c090")]
            public virtual RepoItemInfo RatesResourcesInfo
            {
                get
                {
                    return _ratesresourcesInfo;
                }
            }

            /// <summary>
            /// The SomeList item.
            /// </summary>
            [RepositoryItem("895d9abf-2c7b-455a-9132-0782825fd80f")]
            public virtual Ranorex.List SomeList
            {
                get
                {
                    return _somelistInfo.CreateAdapter<Ranorex.List>(true);
                }
            }

            /// <summary>
            /// The SomeList item info.
            /// </summary>
            [RepositoryItemInfo("895d9abf-2c7b-455a-9132-0782825fd80f")]
            public virtual RepoItemInfo SomeListInfo
            {
                get
                {
                    return _somelistInfo;
                }
            }

            /// <summary>
            /// The PARTCloseButton item.
            /// </summary>
            [RepositoryItem("873f6d9e-7106-4848-9b09-d43163698f2c")]
            public virtual Ranorex.Button PARTCloseButton
            {
                get
                {
                    return _partclosebuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The PARTCloseButton item info.
            /// </summary>
            [RepositoryItemInfo("873f6d9e-7106-4848-9b09-d43163698f2c")]
            public virtual RepoItemInfo PARTCloseButtonInfo
            {
                get
                {
                    return _partclosebuttonInfo;
                }
            }

            /// <summary>
            /// The SomeContainer item.
            /// </summary>
            [RepositoryItem("572f62e6-c31e-4fd5-9cc4-47aae36d2a4e")]
            public virtual Ranorex.Container SomeContainer
            {
                get
                {
                    return _somecontainerInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The SomeContainer item info.
            /// </summary>
            [RepositoryItemInfo("572f62e6-c31e-4fd5-9cc4-47aae36d2a4e")]
            public virtual RepoItemInfo SomeContainerInfo
            {
                get
                {
                    return _somecontainerInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
