///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace FrameworkSolution.ObjectRepository
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the Obj_DataComparison element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("464515c7-46e9-40fa-8f51-a5aeb1de1233")]
    public partial class Obj_DataComparison : RepoGenBaseFolder
    {
        static Obj_DataComparison instance = new Obj_DataComparison();
        Obj_DataComparisonFolders.DriverAppFolder _driver;

        /// <summary>
        /// Gets the singleton class instance representing the Obj_DataComparison element repository.
        /// </summary>
        [RepositoryFolder("464515c7-46e9-40fa-8f51-a5aeb1de1233")]
        public static Obj_DataComparison Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public Obj_DataComparison() 
            : base("Obj_DataComparison", "/", null, 0, false, "464515c7-46e9-40fa-8f51-a5aeb1de1233", ".\\RepositoryImages\\Obj_DataComparison464515c7.rximgres")
        {
            _driver = new Obj_DataComparisonFolders.DriverAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("464515c7-46e9-40fa-8f51-a5aeb1de1233")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The Driver folder.
        /// </summary>
        [RepositoryFolder("5193bedb-fab9-4163-97a2-ef4dd64d0057")]
        public virtual Obj_DataComparisonFolders.DriverAppFolder Driver
        {
            get { return _driver; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class Obj_DataComparisonFolders
    {
        /// <summary>
        /// The DriverAppFolder folder.
        /// </summary>
        [RepositoryFolder("5193bedb-fab9-4163-97a2-ef4dd64d0057")]
        public partial class DriverAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _estimategridcontrolInfo;

            /// <summary>
            /// Creates a new Driver  folder.
            /// </summary>
            public DriverAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Driver", "/form[@classname='Window' and @visible='True' and @automationid='Driver']", parentFolder, 30000, null, true, "5193bedb-fab9-4163-97a2-ef4dd64d0057", "")
            {
                _estimategridcontrolInfo = new RepoItemInfo(this, "EstimateGridControl", "container[@automationid='m_DockLayoutManager']/container[@automationid='m_LayoutGroup']/?/?/container[@automationid='_194be1e9e03d46a3ba78738848364222']//container[@automationid='EstimateGridControl']", 30000, null, "fe71e8ce-50dd-418e-a315-8e510e894a47");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("5193bedb-fab9-4163-97a2-ef4dd64d0057")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("5193bedb-fab9-4163-97a2-ef4dd64d0057")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The EstimateGridControl item.
            /// </summary>
            [RepositoryItem("fe71e8ce-50dd-418e-a315-8e510e894a47")]
            public virtual Ranorex.Container EstimateGridControl
            {
                get
                {
                    return _estimategridcontrolInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The EstimateGridControl item info.
            /// </summary>
            [RepositoryItemInfo("fe71e8ce-50dd-418e-a315-8e510e894a47")]
            public virtual RepoItemInfo EstimateGridControlInfo
            {
                get
                {
                    return _estimategridcontrolInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
