///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace DEstimator
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the DEstimatorRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("7570ec38-db80-4fcc-ac48-2b1d3b01ffd5")]
    public partial class DEstimatorRepository : RepoGenBaseFolder
    {
        static DEstimatorRepository instance = new DEstimatorRepository();

        /// <summary>
        /// Gets the singleton class instance representing the DEstimatorRepository element repository.
        /// </summary>
        [RepositoryFolder("7570ec38-db80-4fcc-ac48-2b1d3b01ffd5")]
        public static DEstimatorRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public DEstimatorRepository() 
            : base("DEstimatorRepository", "/", null, 0, false, "7570ec38-db80-4fcc-ac48-2b1d3b01ffd5", ".\\RepositoryImages\\DEstimatorRepository7570ec38.rximgres")
        {
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("7570ec38-db80-4fcc-ac48-2b1d3b01ffd5")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class DEstimatorRepositoryFolders
    {
    }
#pragma warning restore 0436
}
