///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace FrameworkSolution
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the FrameworkSolutionRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("d4a94e6b-5b4b-475d-aeb4-41a6c45a4da6")]
    public partial class FrameworkSolutionRepository : RepoGenBaseFolder
    {
        static FrameworkSolutionRepository instance = new FrameworkSolutionRepository();
        FrameworkSolutionRepositoryFolders.MailMuhammedBilalOutlookAppFolder _mailmuhammedbilaloutlook;
        FrameworkSolutionRepositoryFolders.FormRunAppFolder _formrun;

        /// <summary>
        /// Gets the singleton class instance representing the FrameworkSolutionRepository element repository.
        /// </summary>
        [RepositoryFolder("d4a94e6b-5b4b-475d-aeb4-41a6c45a4da6")]
        public static FrameworkSolutionRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public FrameworkSolutionRepository() 
            : base("FrameworkSolutionRepository", "/", null, 0, false, "d4a94e6b-5b4b-475d-aeb4-41a6c45a4da6", ".\\RepositoryImages\\FrameworkSolutionRepositoryd4a94e6b.rximgres")
        {
            _mailmuhammedbilaloutlook = new FrameworkSolutionRepositoryFolders.MailMuhammedBilalOutlookAppFolder(this);
            _formrun = new FrameworkSolutionRepositoryFolders.FormRunAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("d4a94e6b-5b4b-475d-aeb4-41a6c45a4da6")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The MailMuhammedBilalOutlook folder.
        /// </summary>
        [RepositoryFolder("63a86d81-16aa-4723-868c-2c85a6757b11")]
        public virtual FrameworkSolutionRepositoryFolders.MailMuhammedBilalOutlookAppFolder MailMuhammedBilalOutlook
        {
            get { return _mailmuhammedbilaloutlook; }
        }

        /// <summary>
        /// The FormRun folder.
        /// </summary>
        [RepositoryFolder("7ec02dfd-6bd1-49e4-8852-6b0c55c7ac5b")]
        public virtual FrameworkSolutionRepositoryFolders.FormRunAppFolder FormRun
        {
            get { return _formrun; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class FrameworkSolutionRepositoryFolders
    {
        /// <summary>
        /// The MailMuhammedBilalOutlookAppFolder folder.
        /// </summary>
        [RepositoryFolder("63a86d81-16aa-4723-868c-2c85a6757b11")]
        public partial class MailMuhammedBilalOutlookAppFolder : RepoGenBaseFolder
        {

            /// <summary>
            /// Creates a new MailMuhammedBilalOutlook  folder.
            /// </summary>
            public MailMuhammedBilalOutlookAppFolder(RepoGenBaseFolder parentFolder) :
                    base("MailMuhammedBilalOutlook", "/dom[@domain='outlook.office.com']", parentFolder, 30000, null, false, "63a86d81-16aa-4723-868c-2c85a6757b11", "")
            {
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("63a86d81-16aa-4723-868c-2c85a6757b11")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("63a86d81-16aa-4723-868c-2c85a6757b11")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }
        }

        /// <summary>
        /// The FormRunAppFolder folder.
        /// </summary>
        [RepositoryFolder("7ec02dfd-6bd1-49e4-8852-6b0c55c7ac5b")]
        public partial class FormRunAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _buttonokInfo;

            /// <summary>
            /// Creates a new FormRun  folder.
            /// </summary>
            public FormRunAppFolder(RepoGenBaseFolder parentFolder) :
                    base("FormRun", "/form[@title='Run']", parentFolder, 30000, null, true, "7ec02dfd-6bd1-49e4-8852-6b0c55c7ac5b", "")
            {
                _buttonokInfo = new RepoItemInfo(this, "ButtonOK", "button[@text='OK']", 30000, null, "62f18c96-e3f7-4a1a-8e5c-6ad610a8ec57");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("7ec02dfd-6bd1-49e4-8852-6b0c55c7ac5b")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("7ec02dfd-6bd1-49e4-8852-6b0c55c7ac5b")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ButtonOK item.
            /// </summary>
            [RepositoryItem("62f18c96-e3f7-4a1a-8e5c-6ad610a8ec57")]
            public virtual Ranorex.Button ButtonOK
            {
                get
                {
                    return _buttonokInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonOK item info.
            /// </summary>
            [RepositoryItemInfo("62f18c96-e3f7-4a1a-8e5c-6ad610a8ec57")]
            public virtual RepoItemInfo ButtonOKInfo
            {
                get
                {
                    return _buttonokInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
