///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace DEstimator.Repository.EstimateView
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the object_Repository_CreateNewEstimate element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("60e10338-cb25-4c70-9d5b-4d868428b272")]
    public partial class object_Repository_CreateNewEstimate : RepoGenBaseFolder
    {
        static object_Repository_CreateNewEstimate instance = new object_Repository_CreateNewEstimate();
        object_Repository_CreateNewEstimateFolders.DriverAppFolder _driver;
        object_Repository_CreateNewEstimateFolders.CreateNewEstimateAppFolder _createnewestimate;

        /// <summary>
        /// Gets the singleton class instance representing the object_Repository_CreateNewEstimate element repository.
        /// </summary>
        [RepositoryFolder("60e10338-cb25-4c70-9d5b-4d868428b272")]
        public static object_Repository_CreateNewEstimate Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public object_Repository_CreateNewEstimate() 
            : base("object_Repository_CreateNewEstimate", "/", null, 0, false, "60e10338-cb25-4c70-9d5b-4d868428b272", ".\\RepositoryImages\\object_Repository_CreateNewEstimate60e10338.rximgres")
        {
            _driver = new object_Repository_CreateNewEstimateFolders.DriverAppFolder(this);
            _createnewestimate = new object_Repository_CreateNewEstimateFolders.CreateNewEstimateAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("60e10338-cb25-4c70-9d5b-4d868428b272")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The Driver folder.
        /// </summary>
        [RepositoryFolder("df43888a-c864-47e5-b26d-02b2bf37e388")]
        public virtual object_Repository_CreateNewEstimateFolders.DriverAppFolder Driver
        {
            get { return _driver; }
        }

        /// <summary>
        /// The CreateNewEstimate folder.
        /// </summary>
        [RepositoryFolder("ce92145b-417b-4785-b79a-711e79b7ec89")]
        public virtual object_Repository_CreateNewEstimateFolders.CreateNewEstimateAppFolder CreateNewEstimate
        {
            get { return _createnewestimate; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class object_Repository_CreateNewEstimateFolders
    {
        /// <summary>
        /// The DriverAppFolder folder.
        /// </summary>
        [RepositoryFolder("df43888a-c864-47e5-b26d-02b2bf37e388")]
        public partial class DriverAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _barbuttonitemlinknewbuttonitemInfo;
            RepoItemInfo _partclosebuttonInfo;

            /// <summary>
            /// Creates a new Driver  folder.
            /// </summary>
            public DriverAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Driver", "/form[@automationid='Driver']", parentFolder, 30000, null, true, "df43888a-c864-47e5-b26d-02b2bf37e388", "")
            {
                _barbuttonitemlinknewbuttonitemInfo = new RepoItemInfo(this, "BarButtonItemLinkNewButtonItem", "container[@automationid='m_RibbonControl']//button[@automationid='BarButtonItemLinkNewButtonItem']", 30000, null, "5df09f4a-df35-469c-8408-3a6387698c7a");
                _partclosebuttonInfo = new RepoItemInfo(this, "PARTCloseButton", "button[@automationid='PART_CloseButton']", 30000, null, "83bed2ae-312b-408a-b9a3-87ee5a2087a2");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("df43888a-c864-47e5-b26d-02b2bf37e388")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("df43888a-c864-47e5-b26d-02b2bf37e388")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The BarButtonItemLinkNewButtonItem item.
            /// </summary>
            [RepositoryItem("5df09f4a-df35-469c-8408-3a6387698c7a")]
            public virtual Ranorex.Button BarButtonItemLinkNewButtonItem
            {
                get
                {
                    return _barbuttonitemlinknewbuttonitemInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The BarButtonItemLinkNewButtonItem item info.
            /// </summary>
            [RepositoryItemInfo("5df09f4a-df35-469c-8408-3a6387698c7a")]
            public virtual RepoItemInfo BarButtonItemLinkNewButtonItemInfo
            {
                get
                {
                    return _barbuttonitemlinknewbuttonitemInfo;
                }
            }

            /// <summary>
            /// The PARTCloseButton item.
            /// </summary>
            [RepositoryItem("83bed2ae-312b-408a-b9a3-87ee5a2087a2")]
            public virtual Ranorex.Button PARTCloseButton
            {
                get
                {
                    return _partclosebuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The PARTCloseButton item info.
            /// </summary>
            [RepositoryItemInfo("83bed2ae-312b-408a-b9a3-87ee5a2087a2")]
            public virtual RepoItemInfo PARTCloseButtonInfo
            {
                get
                {
                    return _partclosebuttonInfo;
                }
            }
        }

        /// <summary>
        /// The CreateNewEstimateAppFolder folder.
        /// </summary>
        [RepositoryFolder("ce92145b-417b-4785-b79a-711e79b7ec89")]
        public partial class CreateNewEstimateAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _partcontenthostInfo;
            RepoItemInfo _createnewbuttonInfo;

            /// <summary>
            /// Creates a new CreateNewEstimate  folder.
            /// </summary>
            public CreateNewEstimateAppFolder(RepoGenBaseFolder parentFolder) :
                    base("CreateNewEstimate", "/form[@title='Create New Estimate']", parentFolder, 30000, null, true, "ce92145b-417b-4785-b79a-711e79b7ec89", "")
            {
                _partcontenthostInfo = new RepoItemInfo(this, "PARTContentHost", ".//text[@automationid='EstimateNameTextEdit']/text[@automationid='PART_Editor']/container[@automationid='PART_ContentHost']", 30000, null, "8946397a-97f8-4a8e-9875-ec5781fca051");
                _createnewbuttonInfo = new RepoItemInfo(this, "CreateNewButton", "button[@automationid='CreateNewButton']", 30000, null, "feef6bc0-e9f7-4898-b16b-d9e079c071e0");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("ce92145b-417b-4785-b79a-711e79b7ec89")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("ce92145b-417b-4785-b79a-711e79b7ec89")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The PARTContentHost item.
            /// </summary>
            [RepositoryItem("8946397a-97f8-4a8e-9875-ec5781fca051")]
            public virtual Ranorex.Container PARTContentHost
            {
                get
                {
                    return _partcontenthostInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The PARTContentHost item info.
            /// </summary>
            [RepositoryItemInfo("8946397a-97f8-4a8e-9875-ec5781fca051")]
            public virtual RepoItemInfo PARTContentHostInfo
            {
                get
                {
                    return _partcontenthostInfo;
                }
            }

            /// <summary>
            /// The CreateNewButton item.
            /// </summary>
            [RepositoryItem("feef6bc0-e9f7-4898-b16b-d9e079c071e0")]
            public virtual Ranorex.Button CreateNewButton
            {
                get
                {
                    return _createnewbuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The CreateNewButton item info.
            /// </summary>
            [RepositoryItemInfo("feef6bc0-e9f7-4898-b16b-d9e079c071e0")]
            public virtual RepoItemInfo CreateNewButtonInfo
            {
                get
                {
                    return _createnewbuttonInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
