///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace Test1
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the Test1Repository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("09d69250-b81d-4cb9-959f-e54c6ce5928b")]
    public partial class Test1Repository : RepoGenBaseFolder
    {
        static Test1Repository instance = new Test1Repository();
        Test1RepositoryFolders.ApplicationUnderTestAppFolder _applicationundertest;

        /// <summary>
        /// Gets the singleton class instance representing the Test1Repository element repository.
        /// </summary>
        [RepositoryFolder("09d69250-b81d-4cb9-959f-e54c6ce5928b")]
        public static Test1Repository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public Test1Repository() 
            : base("Test1Repository", "/", null, 0, false, "09d69250-b81d-4cb9-959f-e54c6ce5928b", ".\\RepositoryImages\\Test1Repository09d69250.rximgres")
        {
            _applicationundertest = new Test1RepositoryFolders.ApplicationUnderTestAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("09d69250-b81d-4cb9-959f-e54c6ce5928b")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The ApplicationUnderTest folder.
        /// </summary>
        [RepositoryFolder("39d4b087-ffe4-40ed-aa2a-c55db7e80686")]
        public virtual Test1RepositoryFolders.ApplicationUnderTestAppFolder ApplicationUnderTest
        {
            get { return _applicationundertest; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class Test1RepositoryFolders
    {
        /// <summary>
        /// The ApplicationUnderTestAppFolder folder.
        /// </summary>
        [RepositoryFolder("39d4b087-ffe4-40ed-aa2a-c55db7e80686")]
        public partial class ApplicationUnderTestAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _newitemInfo;

            /// <summary>
            /// Creates a new ApplicationUnderTest  folder.
            /// </summary>
            public ApplicationUnderTestAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ApplicationUnderTest", "/form[@processname='Estimator']", parentFolder, 30000, null, true, "39d4b087-ffe4-40ed-aa2a-c55db7e80686", "")
            {
                _newitemInfo = new RepoItemInfo(this, "NewItem", "element", 30000, null, "e1efa9ff-108d-42a8-8a8a-dd2a4bb9c107");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("39d4b087-ffe4-40ed-aa2a-c55db7e80686")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("39d4b087-ffe4-40ed-aa2a-c55db7e80686")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The NewItem item.
            /// </summary>
            [RepositoryItem("e1efa9ff-108d-42a8-8a8a-dd2a4bb9c107")]
            public virtual Ranorex.Unknown NewItem
            {
                get
                {
                    return _newitemInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The NewItem item info.
            /// </summary>
            [RepositoryItemInfo("e1efa9ff-108d-42a8-8a8a-dd2a4bb9c107")]
            public virtual RepoItemInfo NewItemInfo
            {
                get
                {
                    return _newitemInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
