///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace FrameworkSolution.ObjectRepository
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the Obj_ImageComparison element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("b0409bbb-90da-4cff-896d-536bf570cb8a")]
    public partial class Obj_ImageComparison : RepoGenBaseFolder
    {
        static Obj_ImageComparison instance = new Obj_ImageComparison();
        Obj_ImageComparisonFolders.CreateNewEstimateAppFolder _createnewestimate;
        Obj_ImageComparisonFolders.DriverAppFolder _driver;
        Obj_ImageComparisonFolders.Driver1AppFolder _driver1;
        RepoItemInfo _dotsInfo;

        /// <summary>
        /// Gets the singleton class instance representing the Obj_ImageComparison element repository.
        /// </summary>
        [RepositoryFolder("b0409bbb-90da-4cff-896d-536bf570cb8a")]
        public static Obj_ImageComparison Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public Obj_ImageComparison() 
            : base("Obj_ImageComparison", "/", null, 0, false, "b0409bbb-90da-4cff-896d-536bf570cb8a", ".\\RepositoryImages\\Obj_ImageComparisonb0409bbb.rximgres")
        {
            _createnewestimate = new Obj_ImageComparisonFolders.CreateNewEstimateAppFolder(this);
            _driver = new Obj_ImageComparisonFolders.DriverAppFolder(this);
            _driver1 = new Obj_ImageComparisonFolders.Driver1AppFolder(this);
            _dotsInfo = new RepoItemInfo(this, "Dots", "/form[@automationid='Driver']/?/?/element[@automationid='m_LoadingDecorator']/container[@automationid='DockLayoutContainer']/?/?/element[@automationid='m_LayoutGroup']/container[@automationid='StartViewLayoutPanel']/?/?/container[@automationid='StartViewUserControl']/?/?/element[@automationid='m_StartPageBackstageView']/element[@automationid='_recentBackstageTabItem']/?/?/container[@automationid='_mruView']/?/?/table[@automationid='_mruGrid']/table/container[@automationid='scr3']//container[@automationid='PART_ScrollContentPresenter']//container[@automationid='gridCards']/container[@automationid='cardsPanel']/?/?/container[@automationid='card']/container[@automationid='gridCardPanel']/container[@automationid='cardHeader']/container/container[1]/container[2]/container[@caption='']/button", 30000, null, "86e7b59f-9e83-4465-a924-f3a5f7420b69");
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("b0409bbb-90da-4cff-896d-536bf570cb8a")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The Dots item.
        /// </summary>
        [RepositoryItem("86e7b59f-9e83-4465-a924-f3a5f7420b69")]
        public virtual Ranorex.Button Dots
        {
            get
            {
                 return _dotsInfo.CreateAdapter<Ranorex.Button>(true);
            }
        }

        /// <summary>
        /// The Dots item info.
        /// </summary>
        [RepositoryItemInfo("86e7b59f-9e83-4465-a924-f3a5f7420b69")]
        public virtual RepoItemInfo DotsInfo
        {
            get
            {
                return _dotsInfo;
            }
        }

        /// <summary>
        /// The CreateNewEstimate folder.
        /// </summary>
        [RepositoryFolder("55827566-43cf-41cf-9c6b-99bb4fb38f22")]
        public virtual Obj_ImageComparisonFolders.CreateNewEstimateAppFolder CreateNewEstimate
        {
            get { return _createnewestimate; }
        }

        /// <summary>
        /// The Driver folder.
        /// </summary>
        [RepositoryFolder("57a1dca7-5f7a-4fa7-a36d-7a45684a510c")]
        public virtual Obj_ImageComparisonFolders.DriverAppFolder Driver
        {
            get { return _driver; }
        }

        /// <summary>
        /// The Driver1 folder.
        /// </summary>
        [RepositoryFolder("7c38d138-eaa1-4a99-bed4-4c4611e31c95")]
        public virtual Obj_ImageComparisonFolders.Driver1AppFolder Driver1
        {
            get { return _driver1; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class Obj_ImageComparisonFolders
    {
        /// <summary>
        /// The CreateNewEstimateAppFolder folder.
        /// </summary>
        [RepositoryFolder("55827566-43cf-41cf-9c6b-99bb4fb38f22")]
        public partial class CreateNewEstimateAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _partcontenthostInfo;
            RepoItemInfo _newestimateInfo;
            RepoItemInfo _partclosebuttonInfo;

            /// <summary>
            /// Creates a new CreateNewEstimate  folder.
            /// </summary>
            public CreateNewEstimateAppFolder(RepoGenBaseFolder parentFolder) :
                    base("CreateNewEstimate", "/form[@visible='True' and @enabled='True']", parentFolder, 30000, null, true, "55827566-43cf-41cf-9c6b-99bb4fb38f22", "")
            {
                _partcontenthostInfo = new RepoItemInfo(this, "PARTContentHost", ".//text[@automationid='EstimateNameTextEdit']/text[@automationid='PART_Editor']/container[@automationid='PART_ContentHost' and @visible='True']", 30000, null, "32c4fc5d-37f4-411f-80ae-f975a2bb5fd4");
                _newestimateInfo = new RepoItemInfo(this, "NewEstimate", "?/?/text[@name='New Estimate' and @text='New Estimate']", 30000, null, "fdd8ff26-15b3-437b-84c0-892c1863a3d2");
                _partclosebuttonInfo = new RepoItemInfo(this, "PARTCloseButton", "button[@automationid='PART_CloseButton' and @visible='True']", 30000, null, "c7afc095-ce80-4e5e-89a4-3ffe2954ad6d");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("55827566-43cf-41cf-9c6b-99bb4fb38f22")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("55827566-43cf-41cf-9c6b-99bb4fb38f22")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The PARTContentHost item.
            /// </summary>
            [RepositoryItem("32c4fc5d-37f4-411f-80ae-f975a2bb5fd4")]
            public virtual Ranorex.Container PARTContentHost
            {
                get
                {
                    return _partcontenthostInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The PARTContentHost item info.
            /// </summary>
            [RepositoryItemInfo("32c4fc5d-37f4-411f-80ae-f975a2bb5fd4")]
            public virtual RepoItemInfo PARTContentHostInfo
            {
                get
                {
                    return _partcontenthostInfo;
                }
            }

            /// <summary>
            /// The NewEstimate item.
            /// </summary>
            [RepositoryItem("fdd8ff26-15b3-437b-84c0-892c1863a3d2")]
            public virtual Ranorex.Text NewEstimate
            {
                get
                {
                    return _newestimateInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The NewEstimate item info.
            /// </summary>
            [RepositoryItemInfo("fdd8ff26-15b3-437b-84c0-892c1863a3d2")]
            public virtual RepoItemInfo NewEstimateInfo
            {
                get
                {
                    return _newestimateInfo;
                }
            }

            /// <summary>
            /// The PARTCloseButton item.
            /// </summary>
            [RepositoryItem("c7afc095-ce80-4e5e-89a4-3ffe2954ad6d")]
            public virtual Ranorex.Button PARTCloseButton
            {
                get
                {
                    return _partclosebuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The PARTCloseButton item info.
            /// </summary>
            [RepositoryItemInfo("c7afc095-ce80-4e5e-89a4-3ffe2954ad6d")]
            public virtual RepoItemInfo PARTCloseButtonInfo
            {
                get
                {
                    return _partclosebuttonInfo;
                }
            }
        }

        /// <summary>
        /// The DriverAppFolder folder.
        /// </summary>
        [RepositoryFolder("57a1dca7-5f7a-4fa7-a36d-7a45684a510c")]
        public partial class DriverAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _buttonnewInfo;
            RepoItemInfo _homescreenInfo;

            /// <summary>
            /// Creates a new Driver  folder.
            /// </summary>
            public DriverAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Driver", "/form[@automationid='Driver' and @processid='5256' and @visibility='Visible' and @type='MainWindow' and @wpfnative='True']", parentFolder, 30000, null, true, "57a1dca7-5f7a-4fa7-a36d-7a45684a510c", "")
            {
                _buttonnewInfo = new RepoItemInfo(this, "ButtonNew", "?/?/element[@automationid='m_RibbonControl']/container[@automationid='PART_AutoHideControl']/container[@automationid='PART_DefaultRibbon']/container[@automationid='PART_MainLayout']/container[@automationid='PART_SelectedPage']/container[@automationid='PART_SelectedPageControlContainer']/list/container[@automationid='root']//container[@automationid='PART_ScrollViewer']/?/?/container[@automationid='PART_ItemsPresenter']/?/?/list/container[@caption='']/container[@caption='']/list/?/?/container/list[1]/?/?/container[@automationid='PART_Border']/?/?/container[@automationid='PART_ItemsPresenter']//button[@text='New']", 30000, null, "9f59c51e-9570-41f1-aedd-e23a6c1f29d0");
                _homescreenInfo = new RepoItemInfo(this, "HomeScreen", "container[@automationid='Root_Grid']/element/element", 30000, null, "34902f4a-5713-44b8-9174-a8fde24fcd4e");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("57a1dca7-5f7a-4fa7-a36d-7a45684a510c")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("57a1dca7-5f7a-4fa7-a36d-7a45684a510c")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ButtonNew item.
            /// </summary>
            [RepositoryItem("9f59c51e-9570-41f1-aedd-e23a6c1f29d0")]
            public virtual Ranorex.Button ButtonNew
            {
                get
                {
                    return _buttonnewInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonNew item info.
            /// </summary>
            [RepositoryItemInfo("9f59c51e-9570-41f1-aedd-e23a6c1f29d0")]
            public virtual RepoItemInfo ButtonNewInfo
            {
                get
                {
                    return _buttonnewInfo;
                }
            }

            /// <summary>
            /// The HomeScreen item.
            /// </summary>
            [RepositoryItem("34902f4a-5713-44b8-9174-a8fde24fcd4e")]
            public virtual Ranorex.Unknown HomeScreen
            {
                get
                {
                    return _homescreenInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The HomeScreen item info.
            /// </summary>
            [RepositoryItemInfo("34902f4a-5713-44b8-9174-a8fde24fcd4e")]
            public virtual RepoItemInfo HomeScreenInfo
            {
                get
                {
                    return _homescreenInfo;
                }
            }
        }

        /// <summary>
        /// The Driver1AppFolder folder.
        /// </summary>
        [RepositoryFolder("7c38d138-eaa1-4a99-bed4-4c4611e31c95")]
        public partial class Driver1AppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _partclosebuttonInfo;

            /// <summary>
            /// Creates a new Driver1  folder.
            /// </summary>
            public Driver1AppFolder(RepoGenBaseFolder parentFolder) :
                    base("Driver1", "/form[@automationid='Driver']", parentFolder, 30000, null, true, "7c38d138-eaa1-4a99-bed4-4c4611e31c95", "")
            {
                _partclosebuttonInfo = new RepoItemInfo(this, "PARTCloseButton", "container[@automationid='Root_Grid']//container[@automationid='PART_Buttons']/container[@automationid='PART_ControlBoxContainer']/?/?/container[@automationid='stackPanel']/container[@automationid='PART_WindowButtons']/button[@automationid='PART_CloseButton']", 30000, null, "a30313ad-419d-4105-bf09-95ae5f211316");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("7c38d138-eaa1-4a99-bed4-4c4611e31c95")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("7c38d138-eaa1-4a99-bed4-4c4611e31c95")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The PARTCloseButton item.
            /// </summary>
            [RepositoryItem("a30313ad-419d-4105-bf09-95ae5f211316")]
            public virtual Ranorex.Button PARTCloseButton
            {
                get
                {
                    return _partclosebuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The PARTCloseButton item info.
            /// </summary>
            [RepositoryItemInfo("a30313ad-419d-4105-bf09-95ae5f211316")]
            public virtual RepoItemInfo PARTCloseButtonInfo
            {
                get
                {
                    return _partclosebuttonInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
