///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace FrameworkSolution.ObjectRepository
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the Obj_CreateEstimate element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("62584774-8ba6-447a-b923-f66904516f35")]
    public partial class Obj_CreateEstimate : RepoGenBaseFolder
    {
        static Obj_CreateEstimate instance = new Obj_CreateEstimate();
        Obj_CreateEstimateFolders.DriverAppFolder _driver;
        Obj_CreateEstimateFolders.CreateNewEstimateAppFolder _createnewestimate;

        /// <summary>
        /// Gets the singleton class instance representing the Obj_CreateEstimate element repository.
        /// </summary>
        [RepositoryFolder("62584774-8ba6-447a-b923-f66904516f35")]
        public static Obj_CreateEstimate Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public Obj_CreateEstimate() 
            : base("Obj_CreateEstimate", "/", null, 0, false, "62584774-8ba6-447a-b923-f66904516f35", ".\\RepositoryImages\\Obj_CreateEstimate62584774.rximgres")
        {
            _driver = new Obj_CreateEstimateFolders.DriverAppFolder(this);
            _createnewestimate = new Obj_CreateEstimateFolders.CreateNewEstimateAppFolder(this);
        }

#region Variables

        string _client = "121";

        /// <summary>
        /// Gets or sets the value of variable client.
        /// </summary>
        [TestVariable("d3bd189a-fa32-4b8f-a9f4-866b2048c2b4")]
        public string client
        {
            get { return _client; }
            set { _client = value; }
        }

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("62584774-8ba6-447a-b923-f66904516f35")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The Driver folder.
        /// </summary>
        [RepositoryFolder("bd87764d-dc1c-4470-a854-2420f4d0dab6")]
        public virtual Obj_CreateEstimateFolders.DriverAppFolder Driver
        {
            get { return _driver; }
        }

        /// <summary>
        /// The CreateNewEstimate folder.
        /// </summary>
        [RepositoryFolder("55827566-43cf-41cf-9c6b-99bb4fb38f22")]
        public virtual Obj_CreateEstimateFolders.CreateNewEstimateAppFolder CreateNewEstimate
        {
            get { return _createnewestimate; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class Obj_CreateEstimateFolders
    {
        /// <summary>
        /// The DriverAppFolder folder.
        /// </summary>
        [RepositoryFolder("bd87764d-dc1c-4470-a854-2420f4d0dab6")]
        public partial class DriverAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _barbuttonitemlinknewbuttonitemInfo;

            /// <summary>
            /// Creates a new Driver  folder.
            /// </summary>
            public DriverAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Driver", "/form[@name='DESTINI Estimator' and @classname='Window']", parentFolder, 30000, null, true, "bd87764d-dc1c-4470-a854-2420f4d0dab6", "")
            {
                _barbuttonitemlinknewbuttonitemInfo = new RepoItemInfo(this, "BarButtonItemLinkNewButtonItem", "container[@automationid='m_RibbonControl']//button[@text='New']", 30000, null, "21a5d928-5bc1-4ccc-91a3-87c96ac76b72");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("bd87764d-dc1c-4470-a854-2420f4d0dab6")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("bd87764d-dc1c-4470-a854-2420f4d0dab6")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The BarButtonItemLinkNewButtonItem item.
            /// </summary>
            [RepositoryItem("21a5d928-5bc1-4ccc-91a3-87c96ac76b72")]
            public virtual Ranorex.Button BarButtonItemLinkNewButtonItem
            {
                get
                {
                    return _barbuttonitemlinknewbuttonitemInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The BarButtonItemLinkNewButtonItem item info.
            /// </summary>
            [RepositoryItemInfo("21a5d928-5bc1-4ccc-91a3-87c96ac76b72")]
            public virtual RepoItemInfo BarButtonItemLinkNewButtonItemInfo
            {
                get
                {
                    return _barbuttonitemlinknewbuttonitemInfo;
                }
            }
        }

        /// <summary>
        /// The CreateNewEstimateAppFolder folder.
        /// </summary>
        [RepositoryFolder("55827566-43cf-41cf-9c6b-99bb4fb38f22")]
        public partial class CreateNewEstimateAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _partcontenthostInfo;
            RepoItemInfo _newestimateInfo;

            /// <summary>
            /// Creates a new CreateNewEstimate  folder.
            /// </summary>
            public CreateNewEstimateAppFolder(RepoGenBaseFolder parentFolder) :
                    base("CreateNewEstimate", "/form[@name='Create New Estimate' and @classname='Window' and @visible='True' and @title='Create New Estimate']", parentFolder, 30000, null, true, "55827566-43cf-41cf-9c6b-99bb4fb38f22", "")
            {
                _partcontenthostInfo = new RepoItemInfo(this, "PARTContentHost", ".//text[@automationid='EstimateNameTextEdit']/text[@automationid='PART_Editor']/container[@visible='True']", 30000, null, "32c4fc5d-37f4-411f-80ae-f975a2bb5fd4");
                _newestimateInfo = new RepoItemInfo(this, "NewEstimate", "?/?/text[@name='New Estimate' and @text='New Estimate']", 30000, null, "fdd8ff26-15b3-437b-84c0-892c1863a3d2");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("55827566-43cf-41cf-9c6b-99bb4fb38f22")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("55827566-43cf-41cf-9c6b-99bb4fb38f22")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The PARTContentHost item.
            /// </summary>
            [RepositoryItem("32c4fc5d-37f4-411f-80ae-f975a2bb5fd4")]
            public virtual Ranorex.Container PARTContentHost
            {
                get
                {
                    return _partcontenthostInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The PARTContentHost item info.
            /// </summary>
            [RepositoryItemInfo("32c4fc5d-37f4-411f-80ae-f975a2bb5fd4")]
            public virtual RepoItemInfo PARTContentHostInfo
            {
                get
                {
                    return _partcontenthostInfo;
                }
            }

            /// <summary>
            /// The NewEstimate item.
            /// </summary>
            [RepositoryItem("fdd8ff26-15b3-437b-84c0-892c1863a3d2")]
            public virtual Ranorex.Text NewEstimate
            {
                get
                {
                    return _newestimateInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The NewEstimate item info.
            /// </summary>
            [RepositoryItemInfo("fdd8ff26-15b3-437b-84c0-892c1863a3d2")]
            public virtual RepoItemInfo NewEstimateInfo
            {
                get
                {
                    return _newestimateInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
