///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace FrameworkSolution.ObjectRepository
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the Obj_AddLineItem_EstimateView element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("31b35080-d82a-4372-a1c4-37386d501f34")]
    public partial class Obj_AddLineItem_EstimateView : RepoGenBaseFolder
    {
        static Obj_AddLineItem_EstimateView instance = new Obj_AddLineItem_EstimateView();
        Obj_AddLineItem_EstimateViewFolders.DriverAppFolder _driver;
        Obj_AddLineItem_EstimateViewFolders.MCostComponentWindowAppFolder _mcostcomponentwindow;
        Obj_AddLineItem_EstimateViewFolders.MConfigureGroupingWindowAppFolder _mconfiguregroupingwindow;
        Obj_AddLineItem_EstimateViewFolders.MTakeoffWindowAppFolder _mtakeoffwindow;

        /// <summary>
        /// Gets the singleton class instance representing the Obj_AddLineItem_EstimateView element repository.
        /// </summary>
        [RepositoryFolder("31b35080-d82a-4372-a1c4-37386d501f34")]
        public static Obj_AddLineItem_EstimateView Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public Obj_AddLineItem_EstimateView() 
            : base("Obj_AddLineItem_EstimateView", "/", null, 0, false, "31b35080-d82a-4372-a1c4-37386d501f34", ".\\RepositoryImages\\Obj_AddLineItem_EstimateView31b35080.rximgres")
        {
            _driver = new Obj_AddLineItem_EstimateViewFolders.DriverAppFolder(this);
            _mcostcomponentwindow = new Obj_AddLineItem_EstimateViewFolders.MCostComponentWindowAppFolder(this);
            _mconfiguregroupingwindow = new Obj_AddLineItem_EstimateViewFolders.MConfigureGroupingWindowAppFolder(this);
            _mtakeoffwindow = new Obj_AddLineItem_EstimateViewFolders.MTakeoffWindowAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("31b35080-d82a-4372-a1c4-37386d501f34")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The Driver folder.
        /// </summary>
        [RepositoryFolder("f6654e3d-3490-4d2d-8e30-632bf996bd3e")]
        public virtual Obj_AddLineItem_EstimateViewFolders.DriverAppFolder Driver
        {
            get { return _driver; }
        }

        /// <summary>
        /// The MCostComponentWindow folder.
        /// </summary>
        [RepositoryFolder("71f95dc3-0dd5-431d-9d6b-511e46db6038")]
        public virtual Obj_AddLineItem_EstimateViewFolders.MCostComponentWindowAppFolder MCostComponentWindow
        {
            get { return _mcostcomponentwindow; }
        }

        /// <summary>
        /// The MConfigureGroupingWindow folder.
        /// </summary>
        [RepositoryFolder("76b67aa1-9a4e-4582-b56c-1e552a3a7a67")]
        public virtual Obj_AddLineItem_EstimateViewFolders.MConfigureGroupingWindowAppFolder MConfigureGroupingWindow
        {
            get { return _mconfiguregroupingwindow; }
        }

        /// <summary>
        /// The MTakeoffWindow folder.
        /// </summary>
        [RepositoryFolder("77338045-5844-49b3-ba7a-a53dc66a349c")]
        public virtual Obj_AddLineItem_EstimateViewFolders.MTakeoffWindowAppFolder MTakeoffWindow
        {
            get { return _mtakeoffwindow; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class Obj_AddLineItem_EstimateViewFolders
    {
        /// <summary>
        /// The DriverAppFolder folder.
        /// </summary>
        [RepositoryFolder("f6654e3d-3490-4d2d-8e30-632bf996bd3e")]
        public partial class DriverAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _baritemlinkaddlineitembuttoncl001addlineInfo;

            /// <summary>
            /// Creates a new Driver  folder.
            /// </summary>
            public DriverAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Driver", "/form[@classname='Window' and @visible='True' and @automationid='Driver']", parentFolder, 30000, null, true, "f6654e3d-3490-4d2d-8e30-632bf996bd3e", "")
            {
                _baritemlinkaddlineitembuttoncl001addlineInfo = new RepoItemInfo(this, "BarItemLinkAddLineItemButtonCL001AddLine", "container[@automationid='m_RibbonControl']//button[@automationid='BarItemLinkAddLineItemButtonCL001AddLineItemButton' and @visible='True' and @text='Add Line Item' and @classname='BarButtonItemLinkControl']", 30000, null, "fece2cde-501d-4227-8aa0-c1a7e9219e03");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("f6654e3d-3490-4d2d-8e30-632bf996bd3e")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("f6654e3d-3490-4d2d-8e30-632bf996bd3e")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The BarItemLinkAddLineItemButtonCL001AddLine item.
            /// </summary>
            [RepositoryItem("fece2cde-501d-4227-8aa0-c1a7e9219e03")]
            public virtual Ranorex.Button BarItemLinkAddLineItemButtonCL001AddLine
            {
                get
                {
                    return _baritemlinkaddlineitembuttoncl001addlineInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The BarItemLinkAddLineItemButtonCL001AddLine item info.
            /// </summary>
            [RepositoryItemInfo("fece2cde-501d-4227-8aa0-c1a7e9219e03")]
            public virtual RepoItemInfo BarItemLinkAddLineItemButtonCL001AddLineInfo
            {
                get
                {
                    return _baritemlinkaddlineitembuttoncl001addlineInfo;
                }
            }
        }

        /// <summary>
        /// The MCostComponentWindowAppFolder folder.
        /// </summary>
        [RepositoryFolder("71f95dc3-0dd5-431d-9d6b-511e46db6038")]
        public partial class MCostComponentWindowAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _imageInfo;
            RepoItemInfo _unclassifieditemsitembeckcontrolsInfo;
            RepoItemInfo _partmaximizeInfo;
            RepoItemInfo _partclosebuttonInfo;

            /// <summary>
            /// Creates a new MCostComponentWindow  folder.
            /// </summary>
            public MCostComponentWindowAppFolder(RepoGenBaseFolder parentFolder) :
                    base("MCostComponentWindow", "/form[@name='Add Line Items' and @classname='Window' and @visible='True']", parentFolder, 30000, null, true, "71f95dc3-0dd5-431d-9d6b-511e46db6038", "")
            {
                _imageInfo = new RepoItemInfo(this, "Image", "container[@automationid='LayoutControl']/container[@automationid='m_TreeGroup']/listitem[@name='LayoutItem' and @classname='LayoutItem' and @text='LayoutItem' and @orientation='None' and @iscontentelement='True' and @iscontrolelement='True' and @iskeyboardfocusable='True']//container[@automationid='LayoutRoot']/?/?/button[@orientation='None' and @iscontentelement='True' and @iscontrolelement='True' and @iskeyboardfocusable='True']/picture[@classname='Image' and @visible='True']", 30000, null, "3828a334-82d7-40d0-a77b-d1ae7db8395f");
                _unclassifieditemsitembeckcontrolsInfo = new RepoItemInfo(this, "UnclassifiedItemsItemBECKControls", "container[@automationid='LayoutControl']/container[@automationid='m_TreeGroup']/listitem[@name='LayoutItem' and @classname='LayoutItem' and @text='LayoutItem' and @orientation='None' and @iscontentelement='True' and @iscontrolelement='True' and @iskeyboardfocusable='True']//container[@automationid='LayoutRoot']/container[@automationid='m_listPanel']//element[@name>'Unclassified Items, Item:' and @visible='True']", 30000, null, "6c703107-5067-412b-b809-a54bd3445bd8");
                _partmaximizeInfo = new RepoItemInfo(this, "PARTMaximize", "button[@automationid='PART_Maximize' and @visible='True' and @classname='Button']", 30000, null, "98ae7fea-ee98-4b01-a861-b764f51684e0");
                _partclosebuttonInfo = new RepoItemInfo(this, "PARTCloseButton", "button[@automationid='PART_CloseButton' and @visible='True' and @classname='Button']", 30000, null, "62b3d747-c33b-4005-84fe-f1b1790caa61");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("71f95dc3-0dd5-431d-9d6b-511e46db6038")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("71f95dc3-0dd5-431d-9d6b-511e46db6038")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Image item.
            /// </summary>
            [RepositoryItem("3828a334-82d7-40d0-a77b-d1ae7db8395f")]
            public virtual Ranorex.Picture Image
            {
                get
                {
                    return _imageInfo.CreateAdapter<Ranorex.Picture>(true);
                }
            }

            /// <summary>
            /// The Image item info.
            /// </summary>
            [RepositoryItemInfo("3828a334-82d7-40d0-a77b-d1ae7db8395f")]
            public virtual RepoItemInfo ImageInfo
            {
                get
                {
                    return _imageInfo;
                }
            }

            /// <summary>
            /// The UnclassifiedItemsItemBECKControls item.
            /// </summary>
            [RepositoryItem("6c703107-5067-412b-b809-a54bd3445bd8")]
            public virtual Ranorex.Unknown UnclassifiedItemsItemBECKControls
            {
                get
                {
                    return _unclassifieditemsitembeckcontrolsInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The UnclassifiedItemsItemBECKControls item info.
            /// </summary>
            [RepositoryItemInfo("6c703107-5067-412b-b809-a54bd3445bd8")]
            public virtual RepoItemInfo UnclassifiedItemsItemBECKControlsInfo
            {
                get
                {
                    return _unclassifieditemsitembeckcontrolsInfo;
                }
            }

            /// <summary>
            /// The PARTMaximize item.
            /// </summary>
            [RepositoryItem("98ae7fea-ee98-4b01-a861-b764f51684e0")]
            public virtual Ranorex.Button PARTMaximize
            {
                get
                {
                    return _partmaximizeInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The PARTMaximize item info.
            /// </summary>
            [RepositoryItemInfo("98ae7fea-ee98-4b01-a861-b764f51684e0")]
            public virtual RepoItemInfo PARTMaximizeInfo
            {
                get
                {
                    return _partmaximizeInfo;
                }
            }

            /// <summary>
            /// The PARTCloseButton item.
            /// </summary>
            [RepositoryItem("62b3d747-c33b-4005-84fe-f1b1790caa61")]
            public virtual Ranorex.Button PARTCloseButton
            {
                get
                {
                    return _partclosebuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The PARTCloseButton item info.
            /// </summary>
            [RepositoryItemInfo("62b3d747-c33b-4005-84fe-f1b1790caa61")]
            public virtual RepoItemInfo PARTCloseButtonInfo
            {
                get
                {
                    return _partclosebuttonInfo;
                }
            }
        }

        /// <summary>
        /// The MConfigureGroupingWindowAppFolder folder.
        /// </summary>
        [RepositoryFolder("76b67aa1-9a4e-4582-b56c-1e552a3a7a67")]
        public partial class MConfigureGroupingWindowAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _collectionclassificationInfo;
            RepoItemInfo _imageInfo;
            RepoItemInfo _textokInfo;

            /// <summary>
            /// Creates a new MConfigureGroupingWindow  folder.
            /// </summary>
            public MConfigureGroupingWindowAppFolder(RepoGenBaseFolder parentFolder) :
                    base("MConfigureGroupingWindow", "/form[@name='Configure Grouping' and @classname='Window' and @visible='True' and @automationid='m_configureGroupingWindow']", parentFolder, 30000, null, true, "76b67aa1-9a4e-4582-b56c-1e552a3a7a67", "")
            {
                _collectionclassificationInfo = new RepoItemInfo(this, "CollectionClassification", "list[@automationid='m_unusedItemsListBox']//text[@name='Collection Classification' and @visible='True' and @text='Collection Classification' and @classname='TextBlock']", 30000, null, "1aec2728-0a47-4c9d-b2ab-83de8659c01a");
                _imageInfo = new RepoItemInfo(this, "Image", "?/?/picture[@classname='Image' and @visible='True' and @automationid='PART_Icon']", 30000, null, "159e9082-e944-4368-ad63-31a33f0da413");
                _textokInfo = new RepoItemInfo(this, "TextOK", "?/?/text[@name='OK' and @visible='True' and @text='OK' and @automationid='PART_Text']", 30000, null, "c7e91f1d-90a2-497e-9128-48b0aa525376");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("76b67aa1-9a4e-4582-b56c-1e552a3a7a67")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("76b67aa1-9a4e-4582-b56c-1e552a3a7a67")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The CollectionClassification item.
            /// </summary>
            [RepositoryItem("1aec2728-0a47-4c9d-b2ab-83de8659c01a")]
            public virtual Ranorex.Text CollectionClassification
            {
                get
                {
                    return _collectionclassificationInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The CollectionClassification item info.
            /// </summary>
            [RepositoryItemInfo("1aec2728-0a47-4c9d-b2ab-83de8659c01a")]
            public virtual RepoItemInfo CollectionClassificationInfo
            {
                get
                {
                    return _collectionclassificationInfo;
                }
            }

            /// <summary>
            /// The Image item.
            /// </summary>
            [RepositoryItem("159e9082-e944-4368-ad63-31a33f0da413")]
            public virtual Ranorex.Picture Image
            {
                get
                {
                    return _imageInfo.CreateAdapter<Ranorex.Picture>(true);
                }
            }

            /// <summary>
            /// The Image item info.
            /// </summary>
            [RepositoryItemInfo("159e9082-e944-4368-ad63-31a33f0da413")]
            public virtual RepoItemInfo ImageInfo
            {
                get
                {
                    return _imageInfo;
                }
            }

            /// <summary>
            /// The TextOK item.
            /// </summary>
            [RepositoryItem("c7e91f1d-90a2-497e-9128-48b0aa525376")]
            public virtual Ranorex.Text TextOK
            {
                get
                {
                    return _textokInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The TextOK item info.
            /// </summary>
            [RepositoryItemInfo("c7e91f1d-90a2-497e-9128-48b0aa525376")]
            public virtual RepoItemInfo TextOKInfo
            {
                get
                {
                    return _textokInfo;
                }
            }
        }

        /// <summary>
        /// The MTakeoffWindowAppFolder folder.
        /// </summary>
        [RepositoryFolder("77338045-5844-49b3-ba7a-a53dc66a349c")]
        public partial class MTakeoffWindowAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _textaddInfo;
            RepoItemInfo _closeInfo;

            /// <summary>
            /// Creates a new MTakeoffWindow  folder.
            /// </summary>
            public MTakeoffWindowAppFolder(RepoGenBaseFolder parentFolder) :
                    base("MTakeoffWindow", "/form[@classname='Window' and @visible='True' and @automationid='m_TakeoffWindow']", parentFolder, 30000, null, true, "77338045-5844-49b3-ba7a-a53dc66a349c", "")
            {
                _textaddInfo = new RepoItemInfo(this, "TextAdd", "?/?/text[@visible='True' and @text='Add']", 30000, null, "4bb4c3ec-6dc0-4ee0-bc0e-07b3639ec44e");
                _closeInfo = new RepoItemInfo(this, "Close", "?/?/text[@visible='True' and @text='Close']", 30000, null, "fca44c7b-caed-42b2-a28e-69933e592402");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("77338045-5844-49b3-ba7a-a53dc66a349c")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("77338045-5844-49b3-ba7a-a53dc66a349c")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The TextAdd item.
            /// </summary>
            [RepositoryItem("4bb4c3ec-6dc0-4ee0-bc0e-07b3639ec44e")]
            public virtual Ranorex.Text TextAdd
            {
                get
                {
                    return _textaddInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The TextAdd item info.
            /// </summary>
            [RepositoryItemInfo("4bb4c3ec-6dc0-4ee0-bc0e-07b3639ec44e")]
            public virtual RepoItemInfo TextAddInfo
            {
                get
                {
                    return _textaddInfo;
                }
            }

            /// <summary>
            /// The Close item.
            /// </summary>
            [RepositoryItem("fca44c7b-caed-42b2-a28e-69933e592402")]
            public virtual Ranorex.Text Close
            {
                get
                {
                    return _closeInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Close item info.
            /// </summary>
            [RepositoryItemInfo("fca44c7b-caed-42b2-a28e-69933e592402")]
            public virtual RepoItemInfo CloseInfo
            {
                get
                {
                    return _closeInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
