///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace FrameworkSolution.ObjectRepository
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the Obj_GenaralClass element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("04d0517a-67ca-470a-9060-c1f50ca9bd87")]
    public partial class Obj_GenaralClass : RepoGenBaseFolder
    {
        static Obj_GenaralClass instance = new Obj_GenaralClass();
        Obj_GenaralClassFolders.DriverAppFolder _driver;

        /// <summary>
        /// Gets the singleton class instance representing the Obj_GenaralClass element repository.
        /// </summary>
        [RepositoryFolder("04d0517a-67ca-470a-9060-c1f50ca9bd87")]
        public static Obj_GenaralClass Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public Obj_GenaralClass() 
            : base("Obj_GenaralClass", "/", null, 0, false, "04d0517a-67ca-470a-9060-c1f50ca9bd87", ".\\RepositoryImages\\Obj_GenaralClass04d0517a.rximgres")
        {
            _driver = new Obj_GenaralClassFolders.DriverAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("04d0517a-67ca-470a-9060-c1f50ca9bd87")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The Driver folder.
        /// </summary>
        [RepositoryFolder("1721f5c8-a3f5-44af-a094-f6cef4d6d892")]
        public virtual Obj_GenaralClassFolders.DriverAppFolder Driver
        {
            get { return _driver; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class Obj_GenaralClassFolders
    {
        /// <summary>
        /// The DriverAppFolder folder.
        /// </summary>
        [RepositoryFolder("1721f5c8-a3f5-44af-a094-f6cef4d6d892")]
        public partial class DriverAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _partclosebuttonInfo;

            /// <summary>
            /// Creates a new Driver  folder.
            /// </summary>
            public DriverAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Driver", "/form[@classname='Window' and @visible='True' and @automationid='Driver']", parentFolder, 30000, null, true, "1721f5c8-a3f5-44af-a094-f6cef4d6d892", "")
            {
                _partclosebuttonInfo = new RepoItemInfo(this, "PARTCloseButton", "button[@automationid='PART_CloseButton' and @visible='True']", 30000, null, "6c994e9f-49f4-47f8-97ac-025714b97bba");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("1721f5c8-a3f5-44af-a094-f6cef4d6d892")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("1721f5c8-a3f5-44af-a094-f6cef4d6d892")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The PARTCloseButton item.
            /// </summary>
            [RepositoryItem("6c994e9f-49f4-47f8-97ac-025714b97bba")]
            public virtual Ranorex.Button PARTCloseButton
            {
                get
                {
                    return _partclosebuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The PARTCloseButton item info.
            /// </summary>
            [RepositoryItemInfo("6c994e9f-49f4-47f8-97ac-025714b97bba")]
            public virtual RepoItemInfo PARTCloseButtonInfo
            {
                get
                {
                    return _partclosebuttonInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
