///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace FrameworkSolution.ObjectRepository
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the Obj_AddAssembly_EstimateView element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("b38d7110-8e5a-497b-83c0-eaf4d1e78a29")]
    public partial class Obj_AddAssembly_EstimateView : RepoGenBaseFolder
    {
        static Obj_AddAssembly_EstimateView instance = new Obj_AddAssembly_EstimateView();
        Obj_AddAssembly_EstimateViewFolders.MConfigureGroupingWindowAppFolder _mconfiguregroupingwindow;
        Obj_AddAssembly_EstimateViewFolders.MTakeoffWindowAppFolder _mtakeoffwindow;
        Obj_AddAssembly_EstimateViewFolders.DriverAppFolder _driver;
        Obj_AddAssembly_EstimateViewFolders.MCostComponentWindowAppFolder _mcostcomponentwindow;

        /// <summary>
        /// Gets the singleton class instance representing the Obj_AddAssembly_EstimateView element repository.
        /// </summary>
        [RepositoryFolder("b38d7110-8e5a-497b-83c0-eaf4d1e78a29")]
        public static Obj_AddAssembly_EstimateView Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public Obj_AddAssembly_EstimateView() 
            : base("Obj_AddAssembly_EstimateView", "/", null, 0, false, "b38d7110-8e5a-497b-83c0-eaf4d1e78a29", ".\\RepositoryImages\\Obj_AddAssembly_EstimateViewb38d7110.rximgres")
        {
            _mconfiguregroupingwindow = new Obj_AddAssembly_EstimateViewFolders.MConfigureGroupingWindowAppFolder(this);
            _mtakeoffwindow = new Obj_AddAssembly_EstimateViewFolders.MTakeoffWindowAppFolder(this);
            _driver = new Obj_AddAssembly_EstimateViewFolders.DriverAppFolder(this);
            _mcostcomponentwindow = new Obj_AddAssembly_EstimateViewFolders.MCostComponentWindowAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("b38d7110-8e5a-497b-83c0-eaf4d1e78a29")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The MConfigureGroupingWindow folder.
        /// </summary>
        [RepositoryFolder("aa180ecc-9688-4d28-9d20-f1f7029f4b00")]
        public virtual Obj_AddAssembly_EstimateViewFolders.MConfigureGroupingWindowAppFolder MConfigureGroupingWindow
        {
            get { return _mconfiguregroupingwindow; }
        }

        /// <summary>
        /// The MTakeoffWindow folder.
        /// </summary>
        [RepositoryFolder("c9d9be3d-18e2-44ce-89d6-102ca72968b7")]
        public virtual Obj_AddAssembly_EstimateViewFolders.MTakeoffWindowAppFolder MTakeoffWindow
        {
            get { return _mtakeoffwindow; }
        }

        /// <summary>
        /// The Driver folder.
        /// </summary>
        [RepositoryFolder("71eb202e-8520-430a-8060-ebf715b9f268")]
        public virtual Obj_AddAssembly_EstimateViewFolders.DriverAppFolder Driver
        {
            get { return _driver; }
        }

        /// <summary>
        /// The MCostComponentWindow folder.
        /// </summary>
        [RepositoryFolder("2eab6c8c-2154-4f7e-a822-784b553d3a5e")]
        public virtual Obj_AddAssembly_EstimateViewFolders.MCostComponentWindowAppFolder MCostComponentWindow
        {
            get { return _mcostcomponentwindow; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class Obj_AddAssembly_EstimateViewFolders
    {
        /// <summary>
        /// The MConfigureGroupingWindowAppFolder folder.
        /// </summary>
        [RepositoryFolder("aa180ecc-9688-4d28-9d20-f1f7029f4b00")]
        public partial class MConfigureGroupingWindowAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _collectionclassificationInfo;
            RepoItemInfo _imageInfo;
            RepoItemInfo _textokInfo;

            /// <summary>
            /// Creates a new MConfigureGroupingWindow  folder.
            /// </summary>
            public MConfigureGroupingWindowAppFolder(RepoGenBaseFolder parentFolder) :
                    base("MConfigureGroupingWindow", "/form[@name='Configure Grouping' and @automationid='m_configureGroupingWindow' and @classname='Window']", parentFolder, 30000, null, true, "aa180ecc-9688-4d28-9d20-f1f7029f4b00", "")
            {
                _collectionclassificationInfo = new RepoItemInfo(this, "CollectionClassification", "list[@automationid='m_unusedItemsListBox']//text[@name='Collection Classification' and @text='Collection Classification']", 30000, null, "0ecf3d4b-4f89-403d-a5cf-4e31a30f6fc6");
                _imageInfo = new RepoItemInfo(this, "Image", "?/?/picture[@classname='Image' and @automationid='PART_Icon']", 30000, null, "55c69126-9148-48ac-bb06-33a8b1362cb1");
                _textokInfo = new RepoItemInfo(this, "TextOK", "?/?/text[@name='OK' and @text='OK' and @classname='TextBlock']", 30000, null, "c3315e70-48f8-4dd7-b048-63049ae73b69");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("aa180ecc-9688-4d28-9d20-f1f7029f4b00")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("aa180ecc-9688-4d28-9d20-f1f7029f4b00")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The CollectionClassification item.
            /// </summary>
            [RepositoryItem("0ecf3d4b-4f89-403d-a5cf-4e31a30f6fc6")]
            public virtual Ranorex.Text CollectionClassification
            {
                get
                {
                    return _collectionclassificationInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The CollectionClassification item info.
            /// </summary>
            [RepositoryItemInfo("0ecf3d4b-4f89-403d-a5cf-4e31a30f6fc6")]
            public virtual RepoItemInfo CollectionClassificationInfo
            {
                get
                {
                    return _collectionclassificationInfo;
                }
            }

            /// <summary>
            /// The Image item.
            /// </summary>
            [RepositoryItem("55c69126-9148-48ac-bb06-33a8b1362cb1")]
            public virtual Ranorex.Picture Image
            {
                get
                {
                    return _imageInfo.CreateAdapter<Ranorex.Picture>(true);
                }
            }

            /// <summary>
            /// The Image item info.
            /// </summary>
            [RepositoryItemInfo("55c69126-9148-48ac-bb06-33a8b1362cb1")]
            public virtual RepoItemInfo ImageInfo
            {
                get
                {
                    return _imageInfo;
                }
            }

            /// <summary>
            /// The TextOK item.
            /// </summary>
            [RepositoryItem("c3315e70-48f8-4dd7-b048-63049ae73b69")]
            public virtual Ranorex.Text TextOK
            {
                get
                {
                    return _textokInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The TextOK item info.
            /// </summary>
            [RepositoryItemInfo("c3315e70-48f8-4dd7-b048-63049ae73b69")]
            public virtual RepoItemInfo TextOKInfo
            {
                get
                {
                    return _textokInfo;
                }
            }
        }

        /// <summary>
        /// The MTakeoffWindowAppFolder folder.
        /// </summary>
        [RepositoryFolder("c9d9be3d-18e2-44ce-89d6-102ca72968b7")]
        public partial class MTakeoffWindowAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _partcontenthostInfo;
            RepoItemInfo _parteditorInfo;
            RepoItemInfo _partitemInfo;
            RepoItemInfo _textaddInfo;
            RepoItemInfo _closeInfo;

            /// <summary>
            /// Creates a new MTakeoffWindow  folder.
            /// </summary>
            public MTakeoffWindowAppFolder(RepoGenBaseFolder parentFolder) :
                    base("MTakeoffWindow", "/form[@name='Assembly Takeoff' and @classname='Window' and @title='Assembly Takeoff']", parentFolder, 30000, null, true, "c9d9be3d-18e2-44ce-89d6-102ca72968b7", "")
            {
                _partcontenthostInfo = new RepoItemInfo(this, "PARTContentHost", "?/?/container[@automationid='m_AssemblyVariablesFormulaFlowLayoutControl']/?/?/text[@automationid='m_VariableValueTextEdit']/?/?/container[@automationid='PART_ContentHost']", 30000, null, "5dfd6f61-bfe1-4fd7-9b2d-9ea968e5f112");
                _parteditorInfo = new RepoItemInfo(this, "PARTEditor", "?/?/list[@automationid='PART_Editor' and @classname='ListBox']", 30000, null, "49b6fb47-3473-47ee-b629-d6e775eec660");
                _partitemInfo = new RepoItemInfo(this, "PARTItem", "?/?/container[@automationid='m_AssemblyVariablesFormulaFlowLayoutControl']/element[2]/text[@automationid='m_VariableValueTextEdit']/button[@automationid='PART_Item']", 30000, null, "16b067b6-5e7a-49f5-ade9-0fd4b76b3b87");
                _textaddInfo = new RepoItemInfo(this, "TextAdd", "?/?/text[@name='Add' and @caption='Add' and @text='Add']", 30000, null, "1c967e36-6447-47e0-9d41-d67aa50cca9e");
                _closeInfo = new RepoItemInfo(this, "Close", "?/?/text[@name='Close' and @caption='Close' and @text='Close']", 30000, null, "2067536a-730f-4587-98f5-bceee36f2724");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("c9d9be3d-18e2-44ce-89d6-102ca72968b7")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("c9d9be3d-18e2-44ce-89d6-102ca72968b7")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The PARTContentHost item.
            /// </summary>
            [RepositoryItem("5dfd6f61-bfe1-4fd7-9b2d-9ea968e5f112")]
            public virtual Ranorex.Container PARTContentHost
            {
                get
                {
                    return _partcontenthostInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The PARTContentHost item info.
            /// </summary>
            [RepositoryItemInfo("5dfd6f61-bfe1-4fd7-9b2d-9ea968e5f112")]
            public virtual RepoItemInfo PARTContentHostInfo
            {
                get
                {
                    return _partcontenthostInfo;
                }
            }

            /// <summary>
            /// The PARTEditor item.
            /// </summary>
            [RepositoryItem("49b6fb47-3473-47ee-b629-d6e775eec660")]
            public virtual Ranorex.List PARTEditor
            {
                get
                {
                    return _parteditorInfo.CreateAdapter<Ranorex.List>(true);
                }
            }

            /// <summary>
            /// The PARTEditor item info.
            /// </summary>
            [RepositoryItemInfo("49b6fb47-3473-47ee-b629-d6e775eec660")]
            public virtual RepoItemInfo PARTEditorInfo
            {
                get
                {
                    return _parteditorInfo;
                }
            }

            /// <summary>
            /// The PARTItem item.
            /// </summary>
            [RepositoryItem("16b067b6-5e7a-49f5-ade9-0fd4b76b3b87")]
            public virtual Ranorex.Button PARTItem
            {
                get
                {
                    return _partitemInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The PARTItem item info.
            /// </summary>
            [RepositoryItemInfo("16b067b6-5e7a-49f5-ade9-0fd4b76b3b87")]
            public virtual RepoItemInfo PARTItemInfo
            {
                get
                {
                    return _partitemInfo;
                }
            }

            /// <summary>
            /// The TextAdd item.
            /// </summary>
            [RepositoryItem("1c967e36-6447-47e0-9d41-d67aa50cca9e")]
            public virtual Ranorex.Text TextAdd
            {
                get
                {
                    return _textaddInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The TextAdd item info.
            /// </summary>
            [RepositoryItemInfo("1c967e36-6447-47e0-9d41-d67aa50cca9e")]
            public virtual RepoItemInfo TextAddInfo
            {
                get
                {
                    return _textaddInfo;
                }
            }

            /// <summary>
            /// The Close item.
            /// </summary>
            [RepositoryItem("2067536a-730f-4587-98f5-bceee36f2724")]
            public virtual Ranorex.Text Close
            {
                get
                {
                    return _closeInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Close item info.
            /// </summary>
            [RepositoryItemInfo("2067536a-730f-4587-98f5-bceee36f2724")]
            public virtual RepoItemInfo CloseInfo
            {
                get
                {
                    return _closeInfo;
                }
            }
        }

        /// <summary>
        /// The DriverAppFolder folder.
        /// </summary>
        [RepositoryFolder("71eb202e-8520-430a-8060-ebf715b9f268")]
        public partial class DriverAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _baritemlinkaddassemblybuttoncl001addasseInfo;
            RepoItemInfo _partmaximizeInfo;

            /// <summary>
            /// Creates a new Driver  folder.
            /// </summary>
            public DriverAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Driver", "/form[@classname='Window' and @automationid='Driver']", parentFolder, 30000, null, true, "71eb202e-8520-430a-8060-ebf715b9f268", "")
            {
                _baritemlinkaddassemblybuttoncl001addasseInfo = new RepoItemInfo(this, "BarItemLinkAddAssemblyButtonCL001AddAsse", "container[@automationid='m_RibbonControl']//button[@text='Add Assembly' and @visible='True' and @classname='RibbonApplicationButtonControl']", 30000, null, "6e993318-c618-4cb3-806c-763f297273dc");
                _partmaximizeInfo = new RepoItemInfo(this, "PARTMaximize", "form[@automationid='m_costComponentWindow']/button[@automationid='PART_Maximize' and @visible='True']", 30000, null, "81f9e041-9e4b-49b3-8618-f187b136a77d");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("71eb202e-8520-430a-8060-ebf715b9f268")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("71eb202e-8520-430a-8060-ebf715b9f268")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The BarItemLinkAddAssemblyButtonCL001AddAsse item.
            /// </summary>
            [RepositoryItem("6e993318-c618-4cb3-806c-763f297273dc")]
            public virtual Ranorex.Button BarItemLinkAddAssemblyButtonCL001AddAsse
            {
                get
                {
                    return _baritemlinkaddassemblybuttoncl001addasseInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The BarItemLinkAddAssemblyButtonCL001AddAsse item info.
            /// </summary>
            [RepositoryItemInfo("6e993318-c618-4cb3-806c-763f297273dc")]
            public virtual RepoItemInfo BarItemLinkAddAssemblyButtonCL001AddAsseInfo
            {
                get
                {
                    return _baritemlinkaddassemblybuttoncl001addasseInfo;
                }
            }

            /// <summary>
            /// The PARTMaximize item.
            /// </summary>
            [RepositoryItem("81f9e041-9e4b-49b3-8618-f187b136a77d")]
            public virtual Ranorex.Button PARTMaximize
            {
                get
                {
                    return _partmaximizeInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The PARTMaximize item info.
            /// </summary>
            [RepositoryItemInfo("81f9e041-9e4b-49b3-8618-f187b136a77d")]
            public virtual RepoItemInfo PARTMaximizeInfo
            {
                get
                {
                    return _partmaximizeInfo;
                }
            }
        }

        /// <summary>
        /// The MCostComponentWindowAppFolder folder.
        /// </summary>
        [RepositoryFolder("2eab6c8c-2154-4f7e-a822-784b553d3a5e")]
        public partial class MCostComponentWindowAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _unclassifieditemsitembeckcontrolsInfo;
            RepoItemInfo _partclosebuttonInfo;

            /// <summary>
            /// Creates a new MCostComponentWindow  folder.
            /// </summary>
            public MCostComponentWindowAppFolder(RepoGenBaseFolder parentFolder) :
                    base("MCostComponentWindow", "/form[@classname='Window' and @visible='True' and @automationid='m_costComponentWindow']", parentFolder, 30000, null, true, "2eab6c8c-2154-4f7e-a822-784b553d3a5e", "")
            {
                _unclassifieditemsitembeckcontrolsInfo = new RepoItemInfo(this, "UnclassifiedItemsItemBECKControls", "container[@automationid='LayoutControl']/container[@automationid='m_TreeGroup']/listitem[@name='LayoutItem' and @classname='LayoutItem' and @text='LayoutItem' and @orientation='None' and @iscontentelement='True' and @iscontrolelement='True' and @iskeyboardfocusable='True']//container[@automationid='LayoutRoot']/container[@automationid='m_listPanel']//element[@visible='True']", 30000, null, "ea24cfa6-8272-42ed-bb63-122a8d35e0d9");
                _partclosebuttonInfo = new RepoItemInfo(this, "PARTCloseButton", "button[@automationid='PART_CloseButton' and @visible='True' and @classname='Button']", 30000, null, "7cbb9b0f-1ed5-4b55-8cc5-646560ef6c09");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("2eab6c8c-2154-4f7e-a822-784b553d3a5e")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("2eab6c8c-2154-4f7e-a822-784b553d3a5e")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The UnclassifiedItemsItemBECKControls item.
            /// </summary>
            [RepositoryItem("ea24cfa6-8272-42ed-bb63-122a8d35e0d9")]
            public virtual Ranorex.Unknown UnclassifiedItemsItemBECKControls
            {
                get
                {
                    return _unclassifieditemsitembeckcontrolsInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The UnclassifiedItemsItemBECKControls item info.
            /// </summary>
            [RepositoryItemInfo("ea24cfa6-8272-42ed-bb63-122a8d35e0d9")]
            public virtual RepoItemInfo UnclassifiedItemsItemBECKControlsInfo
            {
                get
                {
                    return _unclassifieditemsitembeckcontrolsInfo;
                }
            }

            /// <summary>
            /// The PARTCloseButton item.
            /// </summary>
            [RepositoryItem("7cbb9b0f-1ed5-4b55-8cc5-646560ef6c09")]
            public virtual Ranorex.Button PARTCloseButton
            {
                get
                {
                    return _partclosebuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The PARTCloseButton item info.
            /// </summary>
            [RepositoryItemInfo("7cbb9b0f-1ed5-4b55-8cc5-646560ef6c09")]
            public virtual RepoItemInfo PARTCloseButtonInfo
            {
                get
                {
                    return _partclosebuttonInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
