///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace demogit
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the demogitRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("db0492bc-ea08-4455-8742-dd56615c627e")]
    public partial class demogitRepository : RepoGenBaseFolder
    {
        static demogitRepository instance = new demogitRepository();

        /// <summary>
        /// Gets the singleton class instance representing the demogitRepository element repository.
        /// </summary>
        [RepositoryFolder("db0492bc-ea08-4455-8742-dd56615c627e")]
        public static demogitRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public demogitRepository() 
            : base("demogitRepository", "/", null, 0, false, "db0492bc-ea08-4455-8742-dd56615c627e", ".\\RepositoryImages\\demogitRepositorydb0492bc.rximgres")
        {
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("db0492bc-ea08-4455-8742-dd56615c627e")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class demogitRepositoryFolders
    {
    }
#pragma warning restore 0436
}
