///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace FrameworkSolution.DemoObj__Repo
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the AddAssembly element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("4649468f-0777-4a33-ac08-0c01f11d66b7")]
    public partial class AddAssembly : RepoGenBaseFolder
    {
        static AddAssembly instance = new AddAssembly();

        /// <summary>
        /// Gets the singleton class instance representing the AddAssembly element repository.
        /// </summary>
        [RepositoryFolder("4649468f-0777-4a33-ac08-0c01f11d66b7")]
        public static AddAssembly Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public AddAssembly() 
            : base("AddAssembly", "/", null, 0, false, "4649468f-0777-4a33-ac08-0c01f11d66b7", ".\\RepositoryImages\\AddAssembly4649468f.rximgres")
        {
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("4649468f-0777-4a33-ac08-0c01f11d66b7")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class AddAssemblyFolders
    {
    }
#pragma warning restore 0436
}
