///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace FrameworkSolution.DemoObj__Repo
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the AddLine element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("303a8ca2-00ff-495c-92c6-31304d6bab2f")]
    public partial class AddLine : RepoGenBaseFolder
    {
        static AddLine instance = new AddLine();

        /// <summary>
        /// Gets the singleton class instance representing the AddLine element repository.
        /// </summary>
        [RepositoryFolder("303a8ca2-00ff-495c-92c6-31304d6bab2f")]
        public static AddLine Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public AddLine() 
            : base("AddLine", "/", null, 0, false, "303a8ca2-00ff-495c-92c6-31304d6bab2f", ".\\RepositoryImages\\AddLine303a8ca2.rximgres")
        {
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("303a8ca2-00ff-495c-92c6-31304d6bab2f")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class AddLineFolders
    {
    }
#pragma warning restore 0436
}
