///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace FrameworkSolution.DemoObj__Repo
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the CreateEstimate element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("0f350910-8f31-4a03-a7e5-b37acfb57d7e")]
    public partial class CreateEstimate : RepoGenBaseFolder
    {
        static CreateEstimate instance = new CreateEstimate();
        CreateEstimateFolders.DriverAppFolder _driver;
        CreateEstimateFolders.CreateNewEstimateAppFolder _createnewestimate;

        /// <summary>
        /// Gets the singleton class instance representing the CreateEstimate element repository.
        /// </summary>
        [RepositoryFolder("0f350910-8f31-4a03-a7e5-b37acfb57d7e")]
        public static CreateEstimate Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public CreateEstimate() 
            : base("CreateEstimate", "/", null, 0, false, "0f350910-8f31-4a03-a7e5-b37acfb57d7e", ".\\RepositoryImages\\CreateEstimate0f350910.rximgres")
        {
            _driver = new CreateEstimateFolders.DriverAppFolder(this);
            _createnewestimate = new CreateEstimateFolders.CreateNewEstimateAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("0f350910-8f31-4a03-a7e5-b37acfb57d7e")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The Driver folder.
        /// </summary>
        [RepositoryFolder("3e38b402-5b8a-42b1-a14b-416cb305af6c")]
        public virtual CreateEstimateFolders.DriverAppFolder Driver
        {
            get { return _driver; }
        }

        /// <summary>
        /// The CreateNewEstimate folder.
        /// </summary>
        [RepositoryFolder("f2ea2c9f-e7ce-4e8b-913b-b9e01caf6887")]
        public virtual CreateEstimateFolders.CreateNewEstimateAppFolder CreateNewEstimate
        {
            get { return _createnewestimate; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class CreateEstimateFolders
    {
        /// <summary>
        /// The DriverAppFolder folder.
        /// </summary>
        [RepositoryFolder("3e38b402-5b8a-42b1-a14b-416cb305af6c")]
        public partial class DriverAppFolder : RepoGenBaseFolder
        {
            CreateEstimateFolders.DockLayoutContainerFolder _docklayoutcontainer;
            RepoItemInfo _buttonnewInfo;
            RepoItemInfo _partclosebuttonInfo;

            /// <summary>
            /// Creates a new Driver  folder.
            /// </summary>
            public DriverAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Driver", "/form[@automationid='Driver']", parentFolder, 30000, null, true, "3e38b402-5b8a-42b1-a14b-416cb305af6c", "")
            {
                _docklayoutcontainer = new CreateEstimateFolders.DockLayoutContainerFolder(this);
                _buttonnewInfo = new RepoItemInfo(this, "ButtonNew", "?/?/element[@automationid='m_RibbonControl']/container[@automationid='PART_AutoHideControl']/container[@automationid='PART_DefaultRibbon']/container[@automationid='PART_MainLayout']/container[@automationid='PART_SelectedPage']/container[@automationid='PART_SelectedPageControlContainer']/list/container[@automationid='root']//container[@automationid='PART_ScrollViewer']/?/?/container[@automationid='PART_ItemsPresenter']/?/?/list/container[@caption='']/container[@caption='']/list/?/?/container/list[1]/?/?/container[@automationid='PART_Border']/?/?/container[@automationid='PART_ItemsPresenter']//button[@text='New' and @visible='True']", 30000, null, "2c8e8547-dd83-4e68-9a38-04b551b32f07");
                _partclosebuttonInfo = new RepoItemInfo(this, "PARTCloseButton", "container[@automationid='Root_Grid']//container[@automationid='PART_Buttons']/container[@automationid='PART_ControlBoxContainer']/?/?/container[@automationid='stackPanel']/container[@automationid='PART_WindowButtons']/button[@automationid='PART_CloseButton']", 30000, null, "767c6a51-1ddd-4009-b200-b98e9206dbf4");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("3e38b402-5b8a-42b1-a14b-416cb305af6c")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("3e38b402-5b8a-42b1-a14b-416cb305af6c")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ButtonNew item.
            /// </summary>
            [RepositoryItem("2c8e8547-dd83-4e68-9a38-04b551b32f07")]
            public virtual Ranorex.Button ButtonNew
            {
                get
                {
                    return _buttonnewInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonNew item info.
            /// </summary>
            [RepositoryItemInfo("2c8e8547-dd83-4e68-9a38-04b551b32f07")]
            public virtual RepoItemInfo ButtonNewInfo
            {
                get
                {
                    return _buttonnewInfo;
                }
            }

            /// <summary>
            /// The PARTCloseButton item.
            /// </summary>
            [RepositoryItem("767c6a51-1ddd-4009-b200-b98e9206dbf4")]
            public virtual Ranorex.Button PARTCloseButton
            {
                get
                {
                    return _partclosebuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The PARTCloseButton item info.
            /// </summary>
            [RepositoryItemInfo("767c6a51-1ddd-4009-b200-b98e9206dbf4")]
            public virtual RepoItemInfo PARTCloseButtonInfo
            {
                get
                {
                    return _partclosebuttonInfo;
                }
            }

            /// <summary>
            /// The DockLayoutContainer folder.
            /// </summary>
            [RepositoryFolder("956856ea-b257-4f50-9192-25ee0a6efcd3")]
            public virtual CreateEstimateFolders.DockLayoutContainerFolder DockLayoutContainer
            {
                get { return _docklayoutcontainer; }
            }
        }

        /// <summary>
        /// The DockLayoutContainerFolder folder.
        /// </summary>
        [RepositoryFolder("956856ea-b257-4f50-9192-25ee0a6efcd3")]
        public partial class DockLayoutContainerFolder : RepoGenBaseFolder
        {
            RepoItemInfo _mviewerInfo;
            RepoItemInfo _partitemscontrolInfo;
            RepoItemInfo _partloadingpanelInfo;

            /// <summary>
            /// Creates a new DockLayoutContainer  folder.
            /// </summary>
            public DockLayoutContainerFolder(RepoGenBaseFolder parentFolder) :
                    base("DockLayoutContainer", "?/?/element[@automationid='m_LoadingDecorator']/container[@automationid='DockLayoutContainer']", parentFolder, 30000, null, false, "956856ea-b257-4f50-9192-25ee0a6efcd3", "")
            {
                _mviewerInfo = new RepoItemInfo(this, "MViewer", "?/?/element[@automationid='m_LayoutGroup']/?/?/container[@automationid='_26fbb47054604724a1df89c001f16aad']//element[@automationid='m_dockManager']/?/?/container[@automationid='m_loadViewerPanel']//container[@automationid='m_ViewContainer']/container[@automationid='m_ucViewer']/?/?/element[@automationid='m_ViewerGroup']/container[@automationid='m_ViewerPanel']/?/?/container[@automationid='ViewerContainer']/container[@automationid='m_2DCanvas']/picture[@automationid='m_Viewer']", 30000, null, "99710d29-0d07-4ae7-8d06-8cd3370e378c");
                _partitemscontrolInfo = new RepoItemInfo(this, "PARTItemsControl", "?/?/element[@automationid='m_LayoutGroup']/element[@automationid='dockItem1']//container[@automationid='PART_Content']/list[@automationid='PART_ItemsControl']", 30000, null, "102c8364-77b8-4ec3-9059-cf0d3145dbe5");
                _partloadingpanelInfo = new RepoItemInfo(this, "PARTLoadingPanel", "?/?/element[@automationid='m_LayoutGroup']/element[@automationid='dockItem1']/container[@automationid='_26fbb47054604724a1df89c001f16aad']/?/?/container[@automationid='m_ModelViewerView']//element[@automationid='m_dockManager']/?/?/container[@automationid='m_loadViewerPanel']//container[@automationid='m_ViewContainer']/container[@automationid='m_ucViewer']/element[@automationid='m_dockManager']/element[@automationid='m_ViewerGroup']/container[@automationid='m_TakeoffPalette']/?/?/container[@automationid='m_TakeoffPaletteView']//container[@automationid='m_PaletteTreeControl']/element[@automationid='m_dockManager']/?/?/container[@automationid='m_listPanel']/?/?/container[@automationid='m_TreeControlCanvas']//indicator[@visible='True']", 30000, null, "c63c5c36-119a-4642-91f3-cda8a4d582be");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("956856ea-b257-4f50-9192-25ee0a6efcd3")]
            public virtual Ranorex.Container Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("956856ea-b257-4f50-9192-25ee0a6efcd3")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The MViewer item.
            /// </summary>
            [RepositoryItem("99710d29-0d07-4ae7-8d06-8cd3370e378c")]
            public virtual Ranorex.Picture MViewer
            {
                get
                {
                    return _mviewerInfo.CreateAdapter<Ranorex.Picture>(true);
                }
            }

            /// <summary>
            /// The MViewer item info.
            /// </summary>
            [RepositoryItemInfo("99710d29-0d07-4ae7-8d06-8cd3370e378c")]
            public virtual RepoItemInfo MViewerInfo
            {
                get
                {
                    return _mviewerInfo;
                }
            }

            /// <summary>
            /// The PARTItemsControl item.
            /// </summary>
            [RepositoryItem("102c8364-77b8-4ec3-9059-cf0d3145dbe5")]
            public virtual Ranorex.List PARTItemsControl
            {
                get
                {
                    return _partitemscontrolInfo.CreateAdapter<Ranorex.List>(true);
                }
            }

            /// <summary>
            /// The PARTItemsControl item info.
            /// </summary>
            [RepositoryItemInfo("102c8364-77b8-4ec3-9059-cf0d3145dbe5")]
            public virtual RepoItemInfo PARTItemsControlInfo
            {
                get
                {
                    return _partitemscontrolInfo;
                }
            }

            /// <summary>
            /// The PARTLoadingPanel item.
            /// </summary>
            [RepositoryItem("c63c5c36-119a-4642-91f3-cda8a4d582be")]
            public virtual Ranorex.Indicator PARTLoadingPanel
            {
                get
                {
                    return _partloadingpanelInfo.CreateAdapter<Ranorex.Indicator>(true);
                }
            }

            /// <summary>
            /// The PARTLoadingPanel item info.
            /// </summary>
            [RepositoryItemInfo("c63c5c36-119a-4642-91f3-cda8a4d582be")]
            public virtual RepoItemInfo PARTLoadingPanelInfo
            {
                get
                {
                    return _partloadingpanelInfo;
                }
            }
        }

        /// <summary>
        /// The CreateNewEstimateAppFolder folder.
        /// </summary>
        [RepositoryFolder("f2ea2c9f-e7ce-4e8b-913b-b9e01caf6887")]
        public partial class CreateNewEstimateAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _enameInfo;
            RepoItemInfo _clientInfo;
            RepoItemInfo _newestimateInfo;
            RepoItemInfo _exitInfo;
            RepoItemInfo _cancelInfo;

            /// <summary>
            /// Creates a new CreateNewEstimate  folder.
            /// </summary>
            public CreateNewEstimateAppFolder(RepoGenBaseFolder parentFolder) :
                    base("CreateNewEstimate", "/form[@title='Create New Estimate']", parentFolder, 30000, null, true, "f2ea2c9f-e7ce-4e8b-913b-b9e01caf6887", "")
            {
                _enameInfo = new RepoItemInfo(this, "EName", ".//container[@automationid='NewEstimateGroupbox']/?/?/text[@automationid='EstimateNameTextEdit']/container[@automationid='PART_Root']/?/?/element[@automationid='PART_Content']//container[@automationid='PART_ContentHost']/text[@caption='']", 30000, null, "fbe91e85-f33a-40b1-bb40-485f4ff3771d");
                _clientInfo = new RepoItemInfo(this, "Client", ".//container[@automationid='NewEstimateGroupbox']//text[@automationid='_clientName']/container[@automationid='PART_Root']/?/?/element[@automationid='PART_Content']/text[@automationid='PART_Editor']/?/?/container[@automationid='PART_ContentHost']/text[@caption='']", 30000, null, "0fde5583-fab6-4c29-9f25-8d55a57e2f05");
                _newestimateInfo = new RepoItemInfo(this, "NewEstimate", ".//button[@automationid='CreateNewButton']/?/?/container[@automationid='contentPresenter']/text[@caption='New Estimate']", 30000, null, "8e2acbc7-f2ab-43e9-8eaf-1e4e9c62830a");
                _exitInfo = new RepoItemInfo(this, "Exit", "container[@automationid='Root_Grid']/element[@automationid='PART_WindowAdornerDecorator']/container[@automationid='PART_RootContentPresenter']//container[@automationid='PART_RibbonLayout']/container[@automationid='PART_Header']/container[@caption='']/container[2]/container[2]/button[4]", 30000, null, "b61d19de-8b16-468e-a835-70e676d9b74a");
                _cancelInfo = new RepoItemInfo(this, "Cancel", ".//button[@automationid='CancelButton']/?/?/container[@automationid='contentPresenter']/text[@caption='Cancel']", 30000, null, "6e031f43-c4f2-4a72-9567-4d068be2ca28");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("f2ea2c9f-e7ce-4e8b-913b-b9e01caf6887")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("f2ea2c9f-e7ce-4e8b-913b-b9e01caf6887")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The EName item.
            /// </summary>
            [RepositoryItem("fbe91e85-f33a-40b1-bb40-485f4ff3771d")]
            public virtual Ranorex.Text EName
            {
                get
                {
                    return _enameInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The EName item info.
            /// </summary>
            [RepositoryItemInfo("fbe91e85-f33a-40b1-bb40-485f4ff3771d")]
            public virtual RepoItemInfo ENameInfo
            {
                get
                {
                    return _enameInfo;
                }
            }

            /// <summary>
            /// The Client item.
            /// </summary>
            [RepositoryItem("0fde5583-fab6-4c29-9f25-8d55a57e2f05")]
            public virtual Ranorex.Text Client
            {
                get
                {
                    return _clientInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Client item info.
            /// </summary>
            [RepositoryItemInfo("0fde5583-fab6-4c29-9f25-8d55a57e2f05")]
            public virtual RepoItemInfo ClientInfo
            {
                get
                {
                    return _clientInfo;
                }
            }

            /// <summary>
            /// The NewEstimate item.
            /// </summary>
            [RepositoryItem("8e2acbc7-f2ab-43e9-8eaf-1e4e9c62830a")]
            public virtual Ranorex.Text NewEstimate
            {
                get
                {
                    return _newestimateInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The NewEstimate item info.
            /// </summary>
            [RepositoryItemInfo("8e2acbc7-f2ab-43e9-8eaf-1e4e9c62830a")]
            public virtual RepoItemInfo NewEstimateInfo
            {
                get
                {
                    return _newestimateInfo;
                }
            }

            /// <summary>
            /// The Exit item.
            /// </summary>
            [RepositoryItem("b61d19de-8b16-468e-a835-70e676d9b74a")]
            public virtual Ranorex.Button Exit
            {
                get
                {
                    return _exitInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Exit item info.
            /// </summary>
            [RepositoryItemInfo("b61d19de-8b16-468e-a835-70e676d9b74a")]
            public virtual RepoItemInfo ExitInfo
            {
                get
                {
                    return _exitInfo;
                }
            }

            /// <summary>
            /// The Cancel item.
            /// </summary>
            [RepositoryItem("6e031f43-c4f2-4a72-9567-4d068be2ca28")]
            public virtual Ranorex.Text Cancel
            {
                get
                {
                    return _cancelInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Cancel item info.
            /// </summary>
            [RepositoryItemInfo("6e031f43-c4f2-4a72-9567-4d068be2ca28")]
            public virtual RepoItemInfo CancelInfo
            {
                get
                {
                    return _cancelInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
